[[plugins]]
repo = 'lambdalisue/vim-django-support'
on_ft = '''
  python
  python3
  djangohtml
'''


[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = '''
  python
  python3
  djangohtml
'''

[[plugins]]
repo = 'lambdalisue/vim-pyenv'
on_ft = '''
  python
  python3
  djangohtml
'''
