[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Shougo/Unite.vim'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'rsense/rsense'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'marijnh/tern_for_vim'

