[[plugins]]
repo = 'lambdalisue/vim-pyenv'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'stephpy/vim-yaml'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'othree/html5.vim'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'

[[plugins]]
repo = 'ap/vim-css-color'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mizukmb/otenki.vim'

[[plugins]]
repo = 'JulesWang/css.vim'

[[plugins]]
repo = 'mojako/ref-sources.vim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'mustardamus/jqapi'

[[plugins]]
repo = 'tokuhirom/jsref'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'pearofducks/ansible-vim'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'vim-scripts/python.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'ivanov/vim-ipython'
