[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = '''
  python
  python3
'''
hook_add = '''
  autocmd FileType python setlocal completeopt-=preview
  let g:jedi#completions_enabled = 1
  let g:jedi#auto_vim_configuration = 0
  let g:jedi#use_tabs_not_buffers = 1 
  let g:jedi#popup_select_first = 0 
  let g:jedi#popup_on_dot = 1 
  let g:jedi#goto_command = "<C-d>"
  let g:jedi#goto_assignments_command = "<leader>g"
  let g:jedi#goto_definitions_command = ""
  let g:jedi#usages_command = "<leader>n"
  let g:jedi#rename_command = "<leader>R"
'''
